root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/server"
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"
  poll = true
  poll_interval = 1000

[build.post_cmd]
  # goimportsで自動フォーマット
  cmd = "goimports -w ."
  needs_shell = false

[log]
  time = true
